import React, { useState, useEffect } from 'react';
import API from '../api';
import AiChatbot from './AiChatbot';
import { 
  LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, 
  BarChart, Bar, Cell
} from 'recharts';
import { 
  LayoutDashboard, GraduationCap, Calendar, BrainCircuit, Target, Trophy,
  Award, BookOpen, CheckSquare, Sparkles, TrendingUp, Briefcase, 
  AlertTriangle, Compass, RefreshCw, LogOut, CheckCircle2, ChevronRight,
  Plus, Menu
} from 'lucide-react';

export default function StudentDashboard({ user, onLogout }) {
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);
  const [profile, setProfile] = useState(null);
  const [attendance, setAttendance] = useState([]);
  const [marks, setMarks] = useState([]);
  const [remediation, setRemediation] = useState(null);
  const [notifications, setNotifications] = useState([]);
  const [loading, setLoading] = useState(true);

  // Sidebar Tab Navigation State
  const [activeTab, setActiveTab] = useState('overview'); // overview, academics, attendance, aiCounselor, skills, gamification

  // Skill Gap States
  const [targetRole, setTargetRole] = useState('Software Developer');
  const [gapAnalysis, setGapAnalysis] = useState(null);
  const [analyzingGap, setAnalyzingGap] = useState(false);

  // AI Counselor Plan States
  const [generatingPlan, setGeneratingPlan] = useState(false);

  // Form states
  const [newSkill, setNewSkill] = useState('');
  const [skillLevel, setSkillLevel] = useState(3);
  const [addingSkill, setAddingSkill] = useState(false);

  const [newProjTitle, setNewProjTitle] = useState('');
  const [newProjDesc, setNewProjDesc] = useState('');
  const [addingProj, setAddingProj] = useState(false);

  useEffect(() => {
    fetchDashboardData();
  }, []);

  const fetchDashboardData = async () => {
    setLoading(true);
    try {
      const meRes = await API.get('/auth/me');
      setProfile(meRes.data.profile);
      const studentId = meRes.data.user._id || meRes.data.user.id;

      const [attRes, marksRes, remRes, notifRes] = await Promise.all([
        API.get(`/academic/attendance/${studentId}`),
        API.get(`/academic/marks/${studentId}`),
        API.get(`/academic/remediation/${studentId}`),
        API.get(`/academic/notifications`)
      ]);

      setAttendance(attRes.data);
      setMarks(marksRes.data);
      setRemediation(remRes.data);
      setNotifications(notifRes.data);
    } catch (err) {
      console.error('Error fetching dashboard data:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleGenerateAiPlan = async () => {
    setGeneratingPlan(true);
    try {
      const res = await API.post('/ai/action-plan', { studentId: user._id || user.id });
      setRemediation(res.data.remediation);
      alert('AI recovery plan successfully generated by Groq Llama-3!');
    } catch (err) {
      console.error(err);
      alert('Error calling Groq API. Active local fallback plan loaded.');
    } finally {
      setGeneratingPlan(false);
    }
  };

  const handleAnalyzeSkillGap = async () => {
    setAnalyzingGap(true);
    try {
      const res = await API.post('/ai/skill-gap', { targetRole });
      setGapAnalysis(res.data);
    } catch (err) {
      console.error(err);
      alert('Error fetching gap analysis.');
    } finally {
      setAnalyzingGap(false);
    }
  };

  const handleToggleTask = async (taskId, currentStatus) => {
    const nextStatus = currentStatus === 'completed' ? 'assigned' : 'completed';
    try {
      const res = await API.post('/academic/remediation/action', {
        studentId: user._id || user.id,
        taskId,
        status: nextStatus
      });
      setRemediation(res.data);
      // Refresh user details (XP level)
      const meRes = await API.get('/auth/me');
      setProfile(meRes.data.profile);
    } catch (err) {
      console.error(err);
    }
  };

  const handleAddSkill = async (e) => {
    e.preventDefault();
    if (!newSkill) return;
    setAddingSkill(true);
    try {
      const res = await API.post('/academic/portfolio/skills', { name: newSkill, level: skillLevel });
      setProfile(res.data);
      setNewSkill('');
      alert('Skill added successfully!');
    } catch (err) {
      console.error(err);
    } finally {
      setAddingSkill(false);
    }
  };

  const handleAddProject = async (e) => {
    e.preventDefault();
    if (!newProjTitle) return;
    setAddingProj(true);
    try {
      const res = await API.post('/academic/portfolio/achievement', {
        category: 'project',
        title: newProjTitle,
        description: newProjDesc
      });
      setProfile(res.data);
      setNewProjTitle('');
      setNewProjDesc('');
      alert('Project successfully cataloged!');
    } catch (err) {
      console.error(err);
    } finally {
      setAddingProj(false);
    }
  };

  const handleReadNotif = async (notifId) => {
    try {
      await API.post(`/academic/notifications/read/${notifId}`);
      setNotifications(prev => prev.filter(n => n._id !== notifId));
    } catch (err) {
      console.error(err);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-slate-50 text-slate-700">
        <div className="flex flex-col items-center gap-4">
          <div className="w-12 h-12 border-4 border-indigo-600 border-t-transparent rounded-full animate-spin"></div>
          <p className="text-slate-500 font-medium">Loading student workspace...</p>
        </div>
      </div>
    );
  }

  // Attendance metrics
  let totalClasses = 0;
  let attendedClasses = 0;
  const attendanceChartData = attendance.map(a => {
    const present = a.records.filter(r => r.status === 'present').length;
    const total = a.records.length;
    totalClasses += total;
    attendedClasses += present;
    const pct = total > 0 ? (present / total) * 100 : 100;
    return { name: a.courseCode, Attendance: parseFloat(pct.toFixed(1)) };
  });

  const overallAttendancePct = totalClasses > 0 ? (attendedClasses / totalClasses) * 100 : 100;

  const forecastClassesNeeded = () => {
    const target = 75;
    if (overallAttendancePct >= target) return 0;
    return Math.ceil((target * totalClasses - 100 * attendedClasses) / (100 - target));
  };

  const calcPlacementScore = () => {
    if (!profile) return 0;
    const cgpaScore = (profile.cgpa / 10) * 30;
    const skillsScore = Math.min((profile.skills?.length || 0) * 8, 25);
    const projectsScore = Math.min((profile.portfolio?.projects?.length || 0) * 15, 30);
    const attFactor = overallAttendancePct >= 80 ? 15 : (overallAttendancePct / 80) * 15;
    return Math.round(cgpaScore + skillsScore + projectsScore + attFactor);
  };

  const placementScore = calcPlacementScore();

  return (
    <div className="min-h-screen flex bg-slate-50 text-slate-800">
      
      {/* Overlay for mobile sidebar */}
      {isSidebarOpen && (
        <div 
          className="fixed inset-0 bg-slate-950/40 z-45 md:hidden"
          onClick={() => setIsSidebarOpen(false)}
        ></div>
      )}
      
      {/* Sidebar Navigation */}
      <aside className={`fixed inset-y-0 left-0 z-50 w-64 bg-white border-r border-slate-200 flex flex-col transition-transform duration-300 md:translate-x-0 md:static md:h-screen shrink-0 ${isSidebarOpen ? 'translate-x-0' : '-translate-x-full'}`}>
        
        {/* Portal Branding */}
        <div className="p-6 border-b border-slate-100 flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-tr from-indigo-600 to-cyan-500 flex items-center justify-center font-black text-white text-lg shadow-md shadow-indigo-200">
            E
          </div>
          <div>
            <h2 className="font-extrabold text-slate-800 tracking-tight leading-none text-base">EduVision</h2>
            <span className="text-[10px] text-indigo-600 font-semibold tracking-wider uppercase">Student Console</span>
          </div>
        </div>

        {/* Tab Links */}
        <nav className="flex-1 px-4 py-6 space-y-1.5">
          <button
            onClick={() => { setActiveTab('overview'); setIsSidebarOpen(false); }}
            className={`w-full flex items-center gap-3 px-4 py-2.5 rounded-xl text-sm font-semibold transition ${
              activeTab === 'overview' 
                ? 'bg-indigo-50 text-indigo-700' 
                : 'text-slate-500 hover:bg-slate-50 hover:text-slate-800'
            }`}
          >
            <LayoutDashboard className="w-4 h-4" /> Overview Dashboard
          </button>
          
          <button
            onClick={() => { setActiveTab('academics'); setIsSidebarOpen(false); }}
            className={`w-full flex items-center gap-3 px-4 py-2.5 rounded-xl text-sm font-semibold transition ${
              activeTab === 'academics' 
                ? 'bg-indigo-50 text-indigo-700' 
                : 'text-slate-500 hover:bg-slate-50 hover:text-slate-800'
            }`}
          >
            <GraduationCap className="w-4 h-4" /> Academic Records
          </button>

          <button
            onClick={() => { setActiveTab('attendance'); setIsSidebarOpen(false); }}
            className={`w-full flex items-center gap-3 px-4 py-2.5 rounded-xl text-sm font-semibold transition ${
              activeTab === 'attendance' 
                ? 'bg-indigo-50 text-indigo-700' 
                : 'text-slate-500 hover:bg-slate-50 hover:text-slate-800'
            }`}
          >
            <Calendar className="w-4 h-4" /> Attendance Forecast
          </button>

          <button
            onClick={() => { setActiveTab('aiCounselor'); setIsSidebarOpen(false); }}
            className={`w-full flex items-center gap-3 px-4 py-2.5 rounded-xl text-sm font-semibold transition ${
              activeTab === 'aiCounselor' 
                ? 'bg-indigo-50 text-indigo-700' 
                : 'text-slate-500 hover:bg-slate-50 hover:text-slate-800'
            }`}
          >
            <BrainCircuit className="w-4 h-4" /> AI Counselor & Plan
          </button>

          <button
            onClick={() => { setActiveTab('skills'); setIsSidebarOpen(false); }}
            className={`w-full flex items-center gap-3 px-4 py-2.5 rounded-xl text-sm font-semibold transition ${
              activeTab === 'skills' 
                ? 'bg-indigo-50 text-indigo-700' 
                : 'text-slate-500 hover:bg-slate-50 hover:text-slate-800'
            }`}
          >
            <Target className="w-4 h-4" /> Skills & Gap Advisor
          </button>

          <button
            onClick={() => { setActiveTab('gamification'); setIsSidebarOpen(false); }}
            className={`w-full flex items-center gap-3 px-4 py-2.5 rounded-xl text-sm font-semibold transition ${
              activeTab === 'gamification' 
                ? 'bg-indigo-50 text-indigo-700' 
                : 'text-slate-500 hover:bg-slate-50 hover:text-slate-800'
            }`}
          >
            <Trophy className="w-4 h-4" /> Gamification Portal
          </button>
        </nav>

        {/* User profile footer */}
        <div className="p-4 border-t border-slate-100 flex flex-col gap-3">
          <div className="flex items-center gap-3 px-2">
            <div className="w-9 h-9 rounded-full bg-slate-100 flex items-center justify-center font-bold text-indigo-600 text-sm border border-slate-200">
              {user.firstName[0]}{user.lastName[0]}
            </div>
            <div className="truncate">
              <span className="block text-xs font-bold text-slate-800 truncate">{user.firstName} {user.lastName}</span>
              <span className="block text-[10px] text-slate-400 truncate">{profile?.collegeId}</span>
            </div>
          </div>
          <button 
            onClick={onLogout}
            className="w-full flex items-center justify-center gap-2 py-2 bg-slate-100 hover:bg-rose-50 hover:text-rose-600 text-slate-600 rounded-xl text-xs font-semibold transition border border-slate-200/50"
          >
            <LogOut className="w-3.5 h-3.5" /> Sign Out
          </button>
        </div>
      </aside>

      {/* Main Content Area */}
      <main className="flex-1 flex flex-col overflow-y-auto max-h-screen w-full">
        
        {/* Top Header Section */}
        <header className="bg-white border-b border-slate-200 px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <button
              onClick={() => setIsSidebarOpen(true)}
              className="md:hidden p-1.5 hover:bg-slate-100 rounded-lg text-slate-600 transition shrink-0"
              title="Open Menu"
            >
              <Menu className="w-5 h-5" />
            </button>
            <h2 className="text-sm sm:text-lg font-bold text-slate-800 uppercase tracking-tight">
              {activeTab === 'overview' && 'Overview Dashboard'}
              {activeTab === 'academics' && 'Academic Evaluation & Scores'}
              {activeTab === 'attendance' && 'Attendance Forecasting Console'}
              {activeTab === 'aiCounselor' && 'Groq AI Counselor & Action Plan'}
              {activeTab === 'skills' && 'Skills Roster & Career Gap Analysis'}
              {activeTab === 'gamification' && 'Gamified Badges & Points Leaderboard'}
            </h2>
          </div>
          <div className="flex items-center gap-4">
            <button 
              onClick={fetchDashboardData}
              className="p-2 hover:bg-slate-100 rounded-xl text-slate-500 hover:text-slate-800 transition"
              title="Refresh Data"
            >
              <RefreshCw className="w-5 h-5" />
            </button>
          </div>
        </header>

        {/* Content Body */}
        <div className="p-8 space-y-6 w-full">
          
          {/* Active Notifications Alert Bar */}
          {notifications.filter(n => !n.isRead).length > 0 && (
            <div className="space-y-2">
              {notifications.filter(n => !n.isRead).map(notif => (
                <div key={notif._id} className="p-4 rounded-xl border border-rose-200 bg-rose-50 text-rose-800 flex items-center justify-between text-xs sm:text-sm shadow-sm">
                  <div className="flex items-center gap-3">
                    <AlertTriangle className="w-5 h-5 text-rose-600 shrink-0" />
                    <div>
                      <strong className="block text-xs uppercase tracking-wider text-rose-900 font-bold">{notif.type.replace('_', ' ')}</strong>
                      <span className="text-slate-600">{notif.message}</span>
                    </div>
                  </div>
                  <button 
                    onClick={() => handleReadNotif(notif._id)}
                    className="px-2.5 py-1 bg-white hover:bg-rose-100 text-rose-800 border border-rose-200 text-xs rounded-lg transition font-medium"
                  >
                    Dismiss
                  </button>
                </div>
              ))}
            </div>
          )}

          {/* TAB 1: OVERVIEW */}
          {activeTab === 'overview' && (
            <div className="space-y-6">
              
              {/* Telemetry Cards Row */}
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
                
                {/* CGPA Card */}
                <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm flex items-center justify-between">
                  <div>
                    <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider block">Cumulative CGPA</span>
                    <span className="text-4xl font-extrabold text-slate-900 mt-1 block">{(profile?.cgpa || 0.0).toFixed(2)}</span>
                    <span className="text-[10px] text-emerald-600 font-semibold mt-2 block">✓ Semester 1-4 Complete</span>
                  </div>
                  <div className="p-3.5 rounded-xl bg-indigo-50 text-indigo-600">
                    <GraduationCap className="w-6 h-6" />
                  </div>
                </div>

                {/* Attendance Card */}
                <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm flex items-center justify-between">
                  <div>
                    <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider block">Overall Attendance</span>
                    <span className={`text-4xl font-extrabold mt-1 block ${overallAttendancePct >= 75 ? 'text-emerald-600' : 'text-rose-600'}`}>
                      {overallAttendancePct.toFixed(1)}%
                    </span>
                    <span className="text-[10px] text-slate-500 mt-2 block">Threshold requirement: 75%</span>
                  </div>
                  <div className={`p-3.5 rounded-xl ${overallAttendancePct >= 75 ? 'bg-emerald-50 text-emerald-600' : 'bg-rose-50 text-rose-600'}`}>
                    <Calendar className="w-6 h-6" />
                  </div>
                </div>

                {/* Risk Level Card */}
                <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm flex items-center justify-between">
                  <div>
                    <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider block">Risk Assessment</span>
                    <span className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold mt-3 border ${
                      remediation?.riskLevel === 'high' ? 'bg-rose-50 text-rose-700 border-rose-200' :
                      remediation?.riskLevel === 'medium' ? 'bg-amber-50 text-amber-700 border-amber-200' :
                      'bg-emerald-50 text-emerald-700 border-emerald-200'
                    }`}>
                      <span className={`w-2 h-2 rounded-full ${
                        remediation?.riskLevel === 'high' ? 'bg-rose-600' :
                        remediation?.riskLevel === 'medium' ? 'bg-amber-500' :
                        'bg-emerald-500'
                      }`}></span>
                      {remediation?.riskLevel?.toUpperCase() || 'LOW'}
                    </span>
                  </div>
                  <div className="p-3.5 rounded-xl bg-slate-50 text-slate-500">
                    <AlertTriangle className="w-6 h-6" />
                  </div>
                </div>

              </div>

              {/* Placement Readiness Block */}
              <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm grid grid-cols-1 md:grid-cols-12 gap-6 items-center">
                <div className="md:col-span-8 space-y-2">
                  <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
                    <Briefcase className="w-5 h-5 text-indigo-600" /> Placement Readiness Status
                  </h3>
                  <p className="text-xs text-slate-500 leading-relaxed">
                    Evaluates cumulative academic performance, verified skill endorsements, active portfolio counts, and class attendance logs to audit placement clearance index.
                  </p>
                  <div className="pt-2">
                    <span className="text-xs font-semibold text-slate-400 block mb-1">Clearance Checklist Status</span>
                    <div className="flex flex-wrap gap-2 text-[10px] font-bold">
                      <span className="px-2 py-0.5 rounded bg-emerald-50 border border-emerald-200 text-emerald-700">CGPA &gt; 7.5</span>
                      <span className={`px-2 py-0.5 rounded border ${
                        overallAttendancePct >= 75 ? 'bg-emerald-50 border-emerald-200 text-emerald-700' : 'bg-rose-50 border-rose-200 text-rose-700'
                      }`}>Attendance Threshold</span>
                      <span className="px-2 py-0.5 rounded bg-slate-50 border border-slate-200 text-slate-600">Projects Logged</span>
                    </div>
                  </div>
                </div>
                <div className="md:col-span-4 text-center border-l border-slate-100 pl-6 py-2">
                  <div className="inline-flex items-baseline justify-center gap-1">
                    <span className="text-5xl font-black text-indigo-600">{placementScore}</span>
                    <span className="text-sm font-bold text-slate-400">%</span>
                  </div>
                  <span className="block text-xs font-semibold text-slate-400 mt-1 uppercase tracking-wider">Clearance Score</span>
                  <div className="w-full bg-slate-100 rounded-full h-2 mt-3 overflow-hidden">
                    <div className="bg-indigo-600 h-full transition-all" style={{ width: `${placementScore}%` }}></div>
                  </div>
                </div>
              </div>

              {/* Attendance and Grade Overview Mini charts */}
              <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm">
                <h4 className="text-sm font-bold text-slate-800 uppercase tracking-wider mb-4">Subject Attendance Performance</h4>
                <div className="h-60 w-full">
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={attendanceChartData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                      <XAxis dataKey="name" stroke="#94a3b8" fontSize={11} tickLine={false} />
                      <YAxis stroke="#94a3b8" fontSize={11} domain={[0, 100]} tickLine={false} />
                      <Tooltip contentStyle={{ backgroundColor: '#ffffff', border: '1px solid #e2e8f0', borderRadius: 8 }} />
                      <Bar dataKey="Attendance" radius={[4, 4, 0, 0]} barSize={40}>
                        {attendanceChartData.map((entry, index) => (
                          <Cell 
                            key={`cell-${index}`} 
                            fill={entry.Attendance >= 75 ? '#10b981' : entry.Attendance >= 60 ? '#f59e0b' : '#ef4444'} 
                          />
                        ))}
                      </Bar>
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              </div>

            </div>
          )}

          {/* TAB 2: ACADEMICS */}
          {activeTab === 'academics' && (
            <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm space-y-6">
              <div>
                <h3 className="text-lg font-bold text-slate-900">Subject-wise Evaluation Scores</h3>
                <p className="text-xs text-slate-500">View internal assessments, practical evaluations, and final semester grades.</p>
              </div>

              <div className="space-y-4">
                {marks.map((m, idx) => {
                  const finalMark = m.evaluations.find(e => e.type === 'final_semester');
                  const i1 = m.evaluations.find(e => e.type === 'internal_1');
                  const i2 = m.evaluations.find(e => e.type === 'internal_2');
                  const practical = m.evaluations.find(e => e.type === 'practical');

                  return (
                    <div key={idx} className="p-5 rounded-xl bg-slate-50 border border-slate-200">
                      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-2 mb-4">
                        <div>
                          <span className="text-[10px] text-indigo-600 font-bold uppercase tracking-wider">{m.courseCode}</span>
                          <h4 className="text-base font-bold text-slate-800">{m.courseName}</h4>
                        </div>
                        {finalMark && (
                          <div className="bg-indigo-50 border border-indigo-100 px-3.5 py-1.5 rounded-xl text-right">
                            <span className="text-[9px] text-indigo-500 font-bold block uppercase tracking-wider">Final Exam Grade</span>
                            <span className="text-sm font-extrabold text-indigo-700">{finalMark.obtained}/{finalMark.maxMarks}</span>
                          </div>
                        )}
                      </div>
                      
                      {/* Sub marks list */}
                      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 pt-3 border-t border-slate-200/60 text-xs">
                        <div className="flex justify-between items-center bg-white p-3 rounded-lg border border-slate-100">
                          <span className="text-slate-400">Midterm Test 1</span>
                          <strong className="text-slate-800">{i1 ? `${i1.obtained}/${i1.maxMarks}` : 'N/A'}</strong>
                        </div>
                        <div className="flex justify-between items-center bg-white p-3 rounded-lg border border-slate-100">
                          <span className="text-slate-400">Midterm Test 2</span>
                          <strong className="text-slate-800">{i2 ? `${i2.obtained}/${i2.maxMarks}` : 'N/A'}</strong>
                        </div>
                        <div className="flex justify-between items-center bg-white p-3 rounded-lg border border-slate-100">
                          <span className="text-slate-400">Practical Lab Marks</span>
                          <strong className="text-slate-800">{practical ? `${practical.obtained}/${practical.maxMarks}` : 'N/A'}</strong>
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          {/* TAB 3: ATTENDANCE & FORECAST */}
          {activeTab === 'attendance' && (
            <div className="space-y-6">
              
              {/* Overall telemetry */}
              <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div>
                  <h3 className="text-lg font-bold text-slate-900">Attendance Log & Forecasting</h3>
                  <p className="text-xs text-slate-500">Predict future attendance trajectories based on upcoming scheduled classes</p>
                </div>
                <div className="bg-slate-50 border border-slate-200 px-6 py-3 rounded-2xl text-center md:text-right">
                  <span className="text-xs text-slate-400 font-bold block uppercase tracking-wider">Overall Rate</span>
                  <span className={`text-3xl font-extrabold ${overallAttendancePct >= 75 ? 'text-emerald-600' : 'text-rose-600'}`}>
                    {overallAttendancePct.toFixed(1)}%
                  </span>
                </div>
              </div>

              {/* Forecasting calculator results banner */}
              <div className="p-4 rounded-xl border border-indigo-200 bg-indigo-50 text-indigo-900 flex items-center gap-3">
                <TrendingUp className="w-5 h-5 text-indigo-600 shrink-0" />
                <span className="text-xs sm:text-sm font-semibold">
                  {overallAttendancePct >= 75 
                    ? 'Safe Zone Alert: Your attendance meets the regulatory requirements. Keep attending classes to stay above!' 
                    : `Shortage Recovery Target: You need to attend the next ${forecastClassesNeeded()} classes consecutively to cross the 75% bar.`}
                </span>
              </div>

              {/* Subject Breakdown cards */}
              <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm space-y-4">
                <h4 className="text-sm font-bold text-slate-800 uppercase tracking-wider mb-4">Subject Attendance Breakdown</h4>
                {attendance.map((att, idx) => {
                  const present = att.records.filter(r => r.status === 'present').length;
                  const total = att.records.length;
                  const pct = total > 0 ? (present / total) * 100 : 100;

                  return (
                    <div key={idx} className="p-4 rounded-xl bg-slate-50 border border-slate-200 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                      <div>
                        <span className="text-[10px] text-indigo-600 font-bold uppercase">{att.courseCode}</span>
                        <h5 className="text-sm font-bold text-slate-800">{att.courseName}</h5>
                      </div>
                      
                      <div className="flex items-center gap-6 text-xs w-full sm:w-auto justify-between sm:justify-end">
                        <div className="text-right">
                          <span className="text-slate-400 block text-[10px]">Lectures Attended</span>
                          <strong className="text-slate-800">{present} of {total} Conducted</strong>
                        </div>
                        <div className="text-right">
                          <span className="text-slate-400 block text-[10px]">Percentage</span>
                          <strong className={`font-bold ${pct >= 75 ? 'text-emerald-600' : 'text-rose-600'}`}>{pct.toFixed(1)}%</strong>
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>

            </div>
          )}

          {/* TAB 4: AI COUNSELOR */}
          {activeTab === 'aiCounselor' && (
            <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm space-y-6">
              
              {/* Header */}
              <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 border-b border-slate-100 pb-4">
                <div>
                  <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
                    <Sparkles className="w-5 h-5 text-indigo-600" /> Academic Remediation & AI Counseling
                  </h3>
                  <p className="text-xs text-slate-500">AI recovery checklists generated using Groq LLM (Llama-3)</p>
                </div>
                <button
                  onClick={handleGenerateAiPlan}
                  disabled={generatingPlan}
                  className="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 disabled:opacity-50 text-white text-xs font-bold rounded-xl transition flex items-center gap-1.5 shadow-md shadow-indigo-200"
                >
                  <RefreshCw className={`w-3.5 h-3.5 ${generatingPlan ? 'animate-spin' : ''}`} />
                  {generatingPlan ? 'Consulting Counselor...' : 'Re-Generate Recovery Plan'}
                </button>
              </div>

              {/* Advisor Remarks */}
              {remediation?.mentorRemarks && (
                <div className="p-4 rounded-xl bg-slate-50 border border-slate-200">
                  <span className="text-xs text-indigo-600 font-bold uppercase tracking-wider block mb-1">Counselor / Mentor Observations</span>
                  <p className="text-xs text-slate-600 leading-relaxed">{remediation.mentorRemarks}</p>
                </div>
              )}

              {/* Checklist Grid */}
              <div className="space-y-3">
                <span className="text-xs text-slate-400 font-bold uppercase tracking-wider block mb-2">My Active Recovery Actions</span>
                {remediation?.assignedActions?.length > 0 ? (
                  remediation.assignedActions.map((act) => (
                    <div 
                      key={act._id}
                      onClick={() => handleToggleTask(act._id, act.status)}
                      className="flex items-start gap-3 p-3.5 rounded-xl border border-slate-200 hover:border-indigo-300 hover:bg-indigo-50/20 transition cursor-pointer"
                    >
                      <CheckSquare className={`w-5 h-5 shrink-0 mt-0.5 transition ${
                        act.status === 'completed' ? 'text-emerald-600 fill-emerald-50' : 'text-slate-400'
                      }`} />
                      <div className="text-xs">
                        <p className={`font-semibold ${act.status === 'completed' ? 'line-through text-slate-400' : 'text-slate-700'}`}>
                          {act.task}
                        </p>
                        <span className="text-[10px] text-slate-400 block mt-1">Assigned on: {new Date(act.assignedDate).toLocaleDateString()}</span>
                      </div>
                    </div>
                  ))
                ) : (
                  <div className="text-center py-8 text-slate-400 text-xs">
                    No active recovery tasks found. Click 'Re-Generate Recovery Plan' to fetch AI advice.
                  </div>
                )}
              </div>

            </div>
          )}

          {/* TAB 5: SKILLS & GAP ADVISOR */}
          {activeTab === 'skills' && (
            <div className="space-y-6">
              
              {/* AI Gap Analyzer */}
              <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm space-y-4">
                <div>
                  <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
                    <Target className="w-5 h-5 text-indigo-600" /> Career Skill Gap Advisor
                  </h3>
                  <p className="text-xs text-slate-500">Run an AI diagnostics map comparing your skills with industrial target job roles.</p>
                </div>

                <div className="flex flex-col sm:flex-row gap-3">
                  <select
                    value={targetRole}
                    onChange={(e) => setTargetRole(e.target.value)}
                    className="flex-1 px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl outline-none text-sm text-slate-700 focus:border-indigo-500"
                  >
                    <option value="Software Developer">Software Developer</option>
                    <option value="Data Analyst">Data Analyst</option>
                    <option value="AI Engineer">AI Engineer</option>
                    <option value="Cloud Solutions Architect">Cloud Solutions Architect</option>
                  </select>
                  <button
                    onClick={handleAnalyzeSkillGap}
                    disabled={analyzingGap}
                    className="px-6 py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white disabled:opacity-50 text-sm font-semibold rounded-xl transition"
                  >
                    {analyzingGap ? 'Analyzing via Groq...' : 'Audit Target Skills'}
                  </button>
                </div>

                {/* Analysis display */}
                {gapAnalysis && (
                  <div className="p-5 rounded-xl bg-slate-50 border border-slate-200 space-y-4 text-xs">
                    <div className="flex items-center justify-between border-b border-slate-200 pb-3">
                      <span className="font-bold text-slate-700">Match Percentage for {targetRole}:</span>
                      <span className="text-2xl font-black text-indigo-600">{gapAnalysis.roleMatchPercentage}%</span>
                    </div>

                    <div>
                      <span className="text-slate-400 font-bold block mb-2">Missing Skills Target:</span>
                      <div className="flex flex-wrap gap-2">
                        {gapAnalysis.missingSkills?.map((skill, idx) => (
                          <span key={idx} className="px-2.5 py-1 bg-rose-50 border border-rose-200 text-rose-700 rounded-lg font-semibold">
                            {skill.name} ({skill.importance.toUpperCase()})
                          </span>
                        ))}
                      </div>
                    </div>

                    <div className="space-y-3 pt-3 border-t border-slate-200">
                      <span className="text-slate-400 font-bold block">AI Roadmap & recommendations:</span>
                      {gapAnalysis.recommendedRoadmap?.map((phase, idx) => (
                        <div key={idx} className="space-y-1">
                          <h5 className="font-bold text-indigo-600">{phase.phase}</h5>
                          <ul className="list-disc pl-4 text-slate-600 space-y-1">
                            {phase.actions?.map((act, actIdx) => (
                              <li key={actIdx}>{act}</li>
                            ))}
                          </ul>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>

              {/* Skills and Projects portfolio grids */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                
                {/* Skill addition */}
                <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm space-y-4">
                  <h4 className="text-sm font-bold text-slate-800 uppercase tracking-wider">Endorse Skills</h4>
                  
                  <form onSubmit={handleAddSkill} className="space-y-3">
                    <input
                      type="text"
                      placeholder="Skill name, e.g. Docker, SQL"
                      value={newSkill}
                      onChange={(e) => setNewSkill(e.target.value)}
                      className="w-full px-3.5 py-2.5 bg-slate-50 border border-slate-200 rounded-xl outline-none text-xs focus:border-indigo-500"
                    />
                    <div className="flex justify-between items-center text-xs text-slate-500">
                      <label>Competency Level:</label>
                      <select 
                        value={skillLevel}
                        onChange={(e) => setSkillLevel(Number(e.target.value))}
                        className="bg-slate-50 border border-slate-200 px-2 py-1 rounded outline-none"
                      >
                        <option value={1}>1 (Beginner)</option>
                        <option value={2}>2</option>
                        <option value={3}>3 (Intermediate)</option>
                        <option value={4}>4</option>
                        <option value={5}>5 (Expert)</option>
                      </select>
                    </div>
                    <button
                      type="submit"
                      disabled={addingSkill}
                      className="w-full py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl text-xs font-semibold transition"
                    >
                      Add Skill
                    </button>
                  </form>

                  <div className="pt-2">
                    <span className="text-xs text-slate-400 font-bold block mb-2">My Skill Grid</span>
                    <div className="flex flex-wrap gap-1.5">
                      {profile?.skills?.map((sk, idx) => (
                        <span 
                          key={idx}
                          className={`text-xs px-2.5 py-1 rounded-lg border ${
                            sk.verified 
                              ? 'bg-indigo-50 border-indigo-200 text-indigo-700 font-medium' 
                              : 'bg-slate-50 border-slate-200 text-slate-500'
                          }`}
                        >
                          {sk.name} (Lvl {sk.level}) {sk.verified && '✓'}
                        </span>
                      ))}
                    </div>
                  </div>
                </div>

                {/* Project catalog */}
                <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm space-y-4">
                  <h4 className="text-sm font-bold text-slate-800 uppercase tracking-wider">Log Projects</h4>

                  <form onSubmit={handleAddProject} className="space-y-3">
                    <input
                      type="text"
                      placeholder="Project Title"
                      value={newProjTitle}
                      onChange={(e) => setNewProjTitle(e.target.value)}
                      className="w-full px-3.5 py-2.5 bg-slate-50 border border-slate-200 rounded-xl outline-none text-xs focus:border-indigo-500"
                    />
                    <textarea
                      placeholder="Description details..."
                      rows={2}
                      value={newProjDesc}
                      onChange={(e) => setNewProjDesc(e.target.value)}
                      className="w-full px-3.5 py-2.5 bg-slate-50 border border-slate-200 rounded-xl outline-none text-xs focus:border-indigo-500 resize-none"
                    />
                    <button
                      type="submit"
                      disabled={addingProj}
                      className="w-full py-2 bg-cyan-600 hover:bg-cyan-700 text-white rounded-xl text-xs font-semibold transition"
                    >
                      Log Project
                    </button>
                  </form>

                  <div className="pt-2">
                    <span className="text-xs text-slate-400 font-bold block mb-2">My Projects</span>
                    <div className="space-y-2 max-h-36 overflow-y-auto pr-2">
                      {profile?.portfolio?.projects?.map((p, idx) => (
                        <div key={idx} className="p-2.5 rounded-lg bg-slate-50 border border-slate-200 text-[11px]">
                          <h5 className="font-semibold text-slate-800">{p.title}</h5>
                          <p className="text-slate-500 mt-0.5">{p.description}</p>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>

              </div>

            </div>
          )}

          {/* TAB 6: GAMIFICATION */}
          {activeTab === 'gamification' && (
            <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm space-y-6">
              
              <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                <div>
                  <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
                    <Trophy className="w-5 h-5 text-amber-500" /> Gamification Portal
                  </h3>
                  <p className="text-xs text-slate-500">Collect XP logs by maintaining attendance and completing remediation tasks.</p>
                </div>
                <div className="bg-amber-50 border border-amber-100 text-amber-800 px-6 py-2.5 rounded-2xl text-center">
                  <span className="text-xs font-bold block uppercase tracking-wider">Cumulative XP</span>
                  <span className="text-3xl font-black">{profile?.gamification?.xp || 0} XP</span>
                </div>
              </div>

              {/* Progress level */}
              <div className="p-5 rounded-2xl bg-slate-50 border border-slate-200 space-y-2">
                <div className="flex justify-between items-center text-xs">
                  <span className="font-bold text-slate-700">Rank: Level {profile?.gamification?.level || 1} Student</span>
                  <span className="text-slate-400">{500 - ((profile?.gamification?.xp || 0) % 500)} XP to Next Level</span>
                </div>
                <div className="w-full bg-slate-200 rounded-full h-3 overflow-hidden">
                  <div 
                    className="bg-amber-500 h-full transition-all duration-500"
                    style={{ width: `${Math.min(((profile?.gamification?.xp || 0) % 500) / 5, 100)}%` }}
                  ></div>
                </div>
              </div>

              {/* Badges list */}
              <div>
                <span className="text-xs text-slate-400 font-bold uppercase tracking-wider block mb-3">My Trophies & Badges</span>
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-4">
                  {profile?.gamification?.badges?.map((badge, idx) => (
                    <div key={idx} className="p-4 rounded-xl border border-amber-200 bg-amber-50/50 flex flex-col items-center justify-center text-center">
                      <div className="w-12 h-12 rounded-full bg-amber-100 flex items-center justify-center text-lg mb-2 shadow-sm">
                        🏆
                      </div>
                      <span className="text-xs font-bold text-amber-800">{badge}</span>
                      <span className="text-[9px] text-slate-400 mt-1">Verified Endorsement</span>
                    </div>
                  ))}
                </div>
              </div>

            </div>
          )}

        </div>
        
        {/* Floating AI Chatbot Assistant */}
        <AiChatbot studentId={user._id || user.id} placeholderText="Ask EduVision AI about your progress..." />

      </main>
    </div>
  );
}
